// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const prismaDatasourceUrl = process.env.DATABASE_URL || process.env.DIRECT_URL;

if (!prismaDatasourceUrl) {
  throw new Error("Set DATABASE_URL (or DIRECT_URL) before running Prisma commands.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer DATABASE_URL because it's the proven runtime connection on Render.
    // DIRECT_URL still works as fallback when explicitly provided.
    url: prismaDatasourceUrl,
  },
});
