// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const prismaDatasourceUrl = process.env.DIRECT_URL || process.env.DATABASE_URL;

if (!prismaDatasourceUrl) {
  throw new Error("Set DATABASE_URL (or DIRECT_URL) before running Prisma commands.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations should use DIRECT_URL first (direct DB connection).
    // Fallback to DATABASE_URL keeps local/dev resilient.
    url: prismaDatasourceUrl,
  },
});
